### ISSUE TITLE
New Design

### ISSUE THREAD

**Issue by patrickwestwood** [rstgroup/active_i18n#1]

**Comment by patrickwestwood** [comment]
![ted__0000_omfo](https://cloud.githubusercontent.com/assets/6445010/2901297/457c026c-d5d3-11e3-9c19-c842128a4f95.jpg)
![ted__0001_dodawanie](https://cloud.githubusercontent.com/assets/6445010/2901298/457ed726-d5d3-11e3-9099-ada31a184f30.jpg)
![ted__0002_dodane](https://cloud.githubusercontent.com/assets/6445010/2901299/4591b29c-d5d3-11e3-96f6-c6dfa43dde69.jpg)
![ted__0003_lista](https://cloud.githubusercontent.com/assets/6445010/2901300/4596a5e0-d5d3-11e3-95ce-8feed050d3f2.jpg)

**Comment by wojtek-krysiak** [comment]
- One, many few... should be nested in one record not spreaded accros many records
- I need icons for each country - could you make separated sprite with styles?
- In the view you have only one message in a scope. What it will looks like there will be many of them

**Comment by patrickwestwood** [comment]
1. It's one record
2. ok
3. One under another

**Comment by wojtek-krysiak** [comment]
thx @PatrykZ
